# Generated by Django 5.1.3 on 2024-11-09 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('Test', 'Test'), ('ODI', 'ODI'), ('T20', 'T20')], max_length=10)),
                ('match_type_number', models.IntegerField()),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('toss_decision', models.CharField(max_length=10)),
                ('prediction_task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('prediction_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField()),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('runs_batter', models.IntegerField()),
                ('runs_extras', models.IntegerField()),
                ('runs_total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.match')),
                ('batter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_deliveries', to='api.player')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_deliveries', to='api.player')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonstriker_deliveries', to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('players', models.ManyToManyField(related_name='teams', to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='OptimalTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimal_teams', to='api.match')),
                ('players', models.ManyToManyField(related_name='optimal_selections', to='api.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimal_compositions', to='api.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='predicted_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predicted_wins', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='toss_winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toss_wins', to='api.team'),
        ),
    ]
