# Generated by Django 5.1.3 on 2024-11-11 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batter', models.CharField(max_length=100)),
                ('bowler', models.CharField(max_length=100)),
                ('non_striker', models.CharField(max_length=100)),
                ('batter_runs', models.IntegerField()),
                ('extras_runs', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='MatchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balls_per_over', models.IntegerField(default=6)),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('match_type', models.CharField(choices=[('test', 'Test'), ('odi', 'ODI'), ('t20', 'T20')], max_length=10)),
                ('match_type_number', models.IntegerField()),
                ('overs', models.IntegerField()),
                ('season', models.CharField(max_length=20)),
                ('team_type', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=100)),
                ('player_of_match', models.CharField(max_length=100)),
                ('toss_decision', models.CharField(max_length=10)),
                ('toss_winner', models.CharField(max_length=100)),
                ('target_runs', models.IntegerField(blank=True, null=True)),
                ('target_overs', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Match Info',
                'verbose_name_plural': 'Match Info',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_version', models.CharField(max_length=10)),
                ('created', models.DateField()),
                ('revision', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Meta Data',
                'verbose_name_plural': 'Meta Data',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unique_name', models.CharField(max_length=100, unique=True)),
                ('identifier', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('key_bcci', models.CharField(blank=True, max_length=100, null=True)),
                ('key_bcci_2', models.CharField(blank=True, max_length=100, null=True)),
                ('key_bigbash', models.CharField(blank=True, max_length=100, null=True)),
                ('key_cricbuzz', models.CharField(blank=True, max_length=100, null=True)),
                ('key_cricheroes', models.CharField(blank=True, max_length=100, null=True)),
                ('key_crichq', models.CharField(blank=True, max_length=100, null=True)),
                ('key_cricinfo', models.CharField(blank=True, max_length=100, null=True)),
                ('key_cricinfo_2', models.CharField(blank=True, max_length=100, null=True)),
                ('key_cricingif', models.CharField(blank=True, max_length=100, null=True)),
                ('key_cricketarchive', models.CharField(blank=True, max_length=100, null=True)),
                ('key_cricketarchive_2', models.CharField(blank=True, max_length=100, null=True)),
                ('key_cricketworld', models.CharField(blank=True, max_length=100, null=True)),
                ('key_nvplay', models.CharField(blank=True, max_length=100, null=True)),
                ('key_nvplay_2', models.CharField(blank=True, max_length=100, null=True)),
                ('key_opta', models.CharField(blank=True, max_length=100, null=True)),
                ('key_opta_2', models.CharField(blank=True, max_length=100, null=True)),
                ('key_pulse', models.CharField(blank=True, max_length=100, null=True)),
                ('key_pulse_2', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wides', models.IntegerField(blank=True, null=True)),
                ('legbyes', models.IntegerField(blank=True, null=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='api.delivery')),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
            },
        ),
        migrations.CreateModel(
            name='Inning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('match_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='api.matchinfo')),
            ],
            options={
                'verbose_name': 'Inning',
                'verbose_name_plural': 'Innings',
            },
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='meta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.metadata'),
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_referee', models.CharField(blank=True, max_length=100, null=True)),
                ('tv_umpire', models.CharField(blank=True, max_length=100, null=True)),
                ('umpire', models.CharField(max_length=100)),
                ('match_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='api.matchinfo')),
            ],
            options={
                'verbose_name': 'Official',
                'verbose_name_plural': 'Officials',
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('wickets', models.IntegerField(blank=True, null=True)),
                ('winner', models.CharField(max_length=100)),
                ('match_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='api.matchinfo')),
            ],
            options={
                'verbose_name': 'Outcome',
                'verbose_name_plural': 'Outcomes',
            },
        ),
        migrations.CreateModel(
            name='Over',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_number', models.IntegerField()),
                ('inning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overs', to='api.inning')),
            ],
            options={
                'verbose_name': 'Over',
                'verbose_name_plural': 'Overs',
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='over',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.over'),
        ),
        migrations.CreateModel(
            name='Powerplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_over', models.DecimalField(decimal_places=1, max_digits=3)),
                ('to', models.DecimalField(decimal_places=1, max_digits=3)),
                ('powerplay_type', models.CharField(max_length=10)),
                ('match_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powerplays', to='api.matchinfo')),
            ],
            options={
                'verbose_name': 'Powerplay',
                'verbose_name_plural': 'Powerplays',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('players', models.ManyToManyField(related_name='teams', to='api.player')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_a', to='api.team'),
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_b', to='api.team'),
        ),
        migrations.CreateModel(
            name='Wicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=100)),
                ('player_out', models.CharField(max_length=100)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wickets', to='api.delivery')),
                ('fielder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fielders', to='api.player')),
            ],
            options={
                'verbose_name': 'Wicket',
                'verbose_name_plural': 'Wickets',
            },
        ),
    ]
