# Generated by Django 5.1.3 on 2024-11-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='predicted_winner',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='toss_winner',
        ),
        migrations.RemoveField(
            model_name='optimalteam',
            name='match',
        ),
        migrations.RemoveField(
            model_name='optimalteam',
            name='players',
        ),
        migrations.RemoveField(
            model_name='optimalteam',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='OptimalTeam',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
