# Generated by Django 5.1.3 on 2024-11-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_inning_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
