# Generated by Django 5.1.3 on 2024-11-12 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinfo',
            name='team_a_players',
            field=models.ManyToManyField(blank=True, related_name='team_a_matches', to='api.player'),
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='team_b_players',
            field=models.ManyToManyField(blank=True, related_name='team_b_matches', to='api.player'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='batter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_faced', to='api.player'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='bowler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_bowled', to='api.player'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='non_striker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_non_striker', to='api.player'),
        ),
    ]
