# Generated by Django 5.1.3 on 2024-11-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_chat_name_chat_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinfo',
            name='players_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
