# Generated by Django 5.1.3 on 2024-11-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_playerstatistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstatistics',
            old_name='batting_hand',
            new_name='batting',
        ),
        migrations.RenameField(
            model_name='playerstatistics',
            old_name='bowling_hand',
            new_name='bowling',
        ),
    ]
