# Generated by Django 5.1.3 on 2024-11-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_chat_receiver_message_chat_sender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='receiver_message',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender_message',
        ),
        migrations.AddField(
            model_name='chat',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
