# Generated by Django 5.1.3 on 2024-11-30 12:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_matchinfo_amount_to_be_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinfo',
            name='amount_to_be_paid',
            field=models.IntegerField(default=api.models.MatchInfo.random_amount_to_be_paid),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='first_prize',
            field=models.CharField(default=api.models.MatchInfo.random_first_prize, max_length=225),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='prize_pool',
            field=models.CharField(default=api.models.MatchInfo.random_prize_pool, max_length=225),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='teama_spots_left',
            field=models.IntegerField(default=api.models.MatchInfo.random_spots_left),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='teamb_spots_left',
            field=models.IntegerField(default=api.models.MatchInfo.random_spots_left),
        ),
    ]
