# Generated by Django 5.1.3 on 2024-12-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_matchinfo_amount_to_be_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinfo',
            name='inference_row',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
