# Generated by Django 5.1.3 on 2024-12-01 12:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_matchinfo_inference_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinfo',
            name='amount_to_be_paid',
            field=models.IntegerField(blank=True, default=api.models.MatchInfo.random_amount_to_be_paid, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='first_prize',
            field=models.CharField(blank=True, default=api.models.MatchInfo.random_first_prize, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='prize_pool',
            field=models.CharField(blank=True, default=api.models.MatchInfo.random_prize_pool, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='teama_spots_left',
            field=models.IntegerField(blank=True, default=api.models.MatchInfo.random_spots_left, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='teamb_spots_left',
            field=models.IntegerField(blank=True, default=api.models.MatchInfo.random_spots_left, null=True),
        ),
    ]
