# Generated by Django 5.1.3 on 2024-12-01 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_matchinfo_amount_to_be_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinfo',
            name='balls_per_over',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='match_type',
            field=models.CharField(blank=True, choices=[('test', 'Test'), ('odi', 'ODI'), ('t20', 'T20')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='match_type_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='overs',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='player_of_match',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='players_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='season',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='target_overs',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='target_runs',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='team_a',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_a', to='api.team'),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='team_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='toss_decision',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='toss_winner',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='venue',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
