# Generated by Django 5.1.3 on 2024-12-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_matchinfo_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinfo',
            name='team_a',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='matchinfo',
            name='team_a_players',
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='team_b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='matchinfo',
            name='team_b_players',
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='team_a_players',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='team_b_players',
            field=models.TextField(blank=True, null=True),
        ),
    ]
