# Generated by Django 5.1.3 on 2024-12-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_matchinfo_team_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchinfo',
            name='inference_row',
        ),
    ]
