# Generated by Django 5.1.3 on 2024-12-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_matchinfo_inference_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchinfo',
            old_name='teama_spots_left',
            new_name='spots_left',
        ),
        migrations.RemoveField(
            model_name='matchinfo',
            name='teamb_spots_left',
        ),
    ]
