# Generated by Django 5.1.3 on 2024-12-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_delivery_batter_remove_delivery_bowler_and_more'),
        ('api', '0021_rename_teama_spots_left_matchinfo_spots_left_and_more'),
    ]

    operations = [
    ]
