# Generated by Django 5.1.3 on 2024-12-04 13:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_matchinfo_inference_row_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matchinfo",
            old_name="spots_left",
            new_name="teama_spots_left",
        ),
        migrations.AddField(
            model_name="matchinfo",
            name="teamb_spots_left",
            field=models.IntegerField(
                blank=True, default=api.models.MatchInfo.random_spots_left, null=True
            ),
        ),
    ]
