# resources.py
from import_export import resources, fields
from .models import PlayerStatistics

class PlayerStatisticsResource(resources.ModelResource):
    player_name = fields.Field(column_name="Players", attribute="player_name")
    batting = fields.Field(column_name="Batting", attribute="batting")
    bowling = fields.Field(column_name="Bowling", attribute="bowling")
    games = fields.Field(column_name="Games", attribute="games")
    won = fields.Field(column_name="Won", attribute="won")
    drawn = fields.Field(column_name="Drawn", attribute="drawn")
    win_percentage = fields.Field(column_name="Win %", attribute="win_percentage")
    innings_batted = fields.Field(column_name="Innings Batted", attribute="innings_batted")
    runs = fields.Field(column_name="Runs", attribute="runs")
    singles = fields.Field(column_name="Singles", attribute="singles")
    fours = fields.Field(column_name="Fours", attribute="fours")
    sixes = fields.Field(column_name="Sixes", attribute="sixes")
    dot_balls = fields.Field(column_name="Dot Balls", attribute="dot_balls")
    balls_faced = fields.Field(column_name="Balls Faced", attribute="balls_faced")
    outs = fields.Field(column_name="Outs", attribute="outs")
    bowled_outs = fields.Field(column_name="Bowled Outs", attribute="bowled_outs")
    lbw_outs = fields.Field(column_name="LBW Outs", attribute="lbw_outs")
    hitwicket_outs = fields.Field(column_name="Hitwicket Outs", attribute="hitwicket_outs")
    caught_outs = fields.Field(column_name="Caught Outs", attribute="caught_outs")
    stumped_outs = fields.Field(column_name="Stumped Outs", attribute="stumped_outs")
    run_outs = fields.Field(column_name="Run Outs", attribute="run_outs")
    caught_and_bowled_outs = fields.Field(column_name="Caught and Bowled Outs", attribute="caught_and_bowled_outs")
    dot_ball_percentage = fields.Field(column_name="Dot Ball %", attribute="dot_ball_percentage")
    strike_turnover_percentage = fields.Field(column_name="Strike Turnover %", attribute="strike_turnover_percentage")
    batting_sr = fields.Field(column_name="Batting S/R", attribute="batting_sr")
    batting_sr_meanad = fields.Field(column_name="Batting S/R MeanAD", attribute="batting_sr_meanad")
    batting_avg = fields.Field(column_name="Batting Avg", attribute="batting_avg")
    mean_score = fields.Field(column_name="Mean Score", attribute="mean_score")
    score_meanad = fields.Field(column_name="Score MeanAD", attribute="score_meanad")
    scoring_consistency = fields.Field(column_name="Scoring Consistency", attribute="scoring_consistency")
    boundary_percentage = fields.Field(column_name="Boundary %", attribute="boundary_percentage")
    runs_per_ball = fields.Field(column_name="Runs/Ball", attribute="runs_per_ball")
    mean_balls_faced = fields.Field(column_name="Mean Balls Faced", attribute="mean_balls_faced")
    balls_faced_meanad = fields.Field(column_name="Balls Faced MeanAD", attribute="balls_faced_meanad")
    survival_consistency = fields.Field(column_name="Survival Consistency", attribute="survival_consistency")
    avg_first_boundary_ball = fields.Field(column_name="Avg First Boundary Ball", attribute="avg_first_boundary_ball")
    dismissal_rate = fields.Field(column_name="Dismissal Rate", attribute="dismissal_rate")
    boundary_rate = fields.Field(column_name="Boundary Rate", attribute="boundary_rate")
    innings_bowled = fields.Field(column_name="Innings Bowled", attribute="innings_bowled")
    runs_given = fields.Field(column_name="Runsgiven", attribute="runs_given")
    singles_given = fields.Field(column_name="Singlesgiven", attribute="singles_given")
    fours_given = fields.Field(column_name="Foursgiven", attribute="fours_given")
    sixes_given = fields.Field(column_name="Sixesgiven", attribute="sixes_given")
    wickets = fields.Field(column_name="Wickets", attribute="wickets")
    balls_bowled = fields.Field(column_name="Balls Bowled", attribute="balls_bowled")
    extras = fields.Field(column_name="Extras", attribute="extras")
    no_balls = fields.Field(column_name="No Balls", attribute="no_balls")
    wides = fields.Field(column_name="Wides", attribute="wides")
    dot_balls_bowled = fields.Field(column_name="Dot Balls Bowled", attribute="dot_balls_bowled")
    bowleds = fields.Field(column_name="Bowleds", attribute="bowleds")
    lbws = fields.Field(column_name="LBWs", attribute="lbws")
    hitwickets = fields.Field(column_name="Hitwickets", attribute="hitwickets")
    caughts = fields.Field(column_name="Caughts", attribute="caughts")
    stumpeds = fields.Field(column_name="Stumpeds", attribute="stumpeds")
    caught_and_bowleds = fields.Field(column_name="Caught and Bowleds", attribute="caught_and_bowleds")
    catches = fields.Field(column_name="Catches", attribute="catches")
    runouts = fields.Field(column_name="Runouts", attribute="runouts")
    stumpings = fields.Field(column_name="Stumpings", attribute="stumpings")
    economy_rate = fields.Field(column_name="Economy Rate", attribute="economy_rate")
    economy_rate_meanad = fields.Field(column_name="Economy Rate MeanAD", attribute="economy_rate_meanad")
    dot_ball_bowled_percentage = fields.Field(column_name="Dot Ball Bowled %", attribute="dot_ball_bowled_percentage")
    boundary_given_percentage = fields.Field(column_name="Boundary Given %", attribute="boundary_given_percentage")
    bowling_avg = fields.Field(column_name="Bowling Avg", attribute="bowling_avg")
    bowling_avg_meanad = fields.Field(column_name="Bowling Avg MeanAD", attribute="bowling_avg_meanad")
    bowling_sr = fields.Field(column_name="Bowling S/R", attribute="bowling_sr")
    bowling_sr_meanad = fields.Field(column_name="Bowling S/R MeanAD", attribute="bowling_sr_meanad")
    runs_given_per_ball = fields.Field(column_name="Runsgiven/Ball", attribute="runs_given_per_ball")
    boundary_given_rate = fields.Field(column_name="Boundary Given Rate", attribute="boundary_given_rate")
    strike_turnover_given_percentage = fields.Field(column_name="Strike Turnovergiven %", attribute="strike_turnover_given_percentage")
    avg_consecutive_dot_balls = fields.Field(column_name="Avg Consecutive Dot Balls", attribute="avg_consecutive_dot_balls")
    runs_rate = fields.Field(column_name="Runs Rate", attribute="runs_rate")
    runs_given_per_wicket = fields.Field(column_name="Runsgiven/Wicket", attribute="runs_given_per_wicket")
    runs_aa = fields.Field(column_name="Runs AA", attribute="runs_aa")
    runs_per_ball_aa = fields.Field(column_name="Runs/Ball AA", attribute="runs_per_ball_aa")
    runs_given_aa = fields.Field(column_name="Runsgiven AA", attribute="runs_given_aa")
    runs_given_per_ball_aa = fields.Field(column_name="Runsgiven/Ball AA", attribute="runs_given_per_ball_aa")

    class Meta:
        model = PlayerStatistics
        skip_unchanged = True
        report_skipped = True
        import_id_fields = ['player_name']
        
